In [5]:
# Install required pacakages
!pip install rouge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting rouge
  Downloading rouge-1.0.1-py3-none-any.whl (13 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from rouge) (1.16.0)
Installing collected packages: rouge
Successfully installed rouge-1.0.1

In [1]:
# Mount the drive if running on colab 
from google.colab import drive
drive.mount('/content/drive')
# Import other required libraries 
import pandas as pd
import locale
locale.getpreferredencoding = lambda: "UTF-8"
from rouge import Rouge
ROUGE = Rouge()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
# Read the dataset after generating summaries
data_to_test = pd.read_excel('/content/drive/MyDrive/summary_all_complete.xlsx')
data_to_test.head(1)

,xml_filepath,title,summary,description,duration_minutes,duration_seconds,show_filename_prefix,episode_filename_prefix,json_filepath,json_transcript,summary_25,summary_3,summary_35,fb_transcript_summary,fb_summary_25,fb_summary_3,fb_summary_35
0,/content/drive/MyDrive/TREC/spotify-podcasts-2...,Ep.05 Why We Don't Sell Presets,<p>Today on the podcast we go on a JOURNEY! We...,<p>Today on the podcast we go on a JOURNEY! We...,3256,54.2712,show_015DbLwcXu2fK7e9jIfbFo,74t5WREXUbhEKNI89CNSkL,/content/drive/MyDrive/TREC/spotify-podcasts-2...,Welcome back to another episode of tuxedo tim...,Welcome back to another episode of tuxedo time...,Welcome back to another episode of tuxedo time...,Welcome back to another episode of tuxedo time...,We're back with another episode of Tuxedos. It...,It's time for another episode of Tuxedos. We'r...,"In our last episode of Tuxedos, we were sittin...",It's been a while since we've recorded a podca...

In [21]:
# Code to get the rogue scores 
def get_rogue_scores(row):
  # change indices depending on the columns to compare
  # rouge_scores = ROUGE.get_scores(row[14], row[13])
  # rouge_scores = ROUGE.get_scores(row[15], row[13])
  # rouge_scores = ROUGE.get_scores(row[16], row[13])
  # rouge_scores = ROUGE.get_scores(row[10], row[2])
  # rouge_scores = ROUGE.get_scores(row[11], row[2])
  rouge_scores = ROUGE.get_scores(row[12], row[2])
  r1 = list(rouge_scores[0].values())[0]['r']
  rl = list(rouge_scores[0].values())[2]['r']
  return [r1, rl]

In [ ]:
# Edit the get_rogue_scores function before running each cell from the in the next 6 cells

In [12]:
data_to_test['fb_25_scores'] = data_to_test.apply(get_rogue_scores, axis=1) # rouge_scores = ROUGE.get_scores(row[14], row[13])

In [14]:
data_to_test['fb_30_scores'] = data_to_test.apply(get_rogue_scores, axis=1) # rouge_scores = ROUGE.get_scores(row[15], row[13])

In [16]:
data_to_test['fb_35_scores'] = data_to_test.apply(get_rogue_scores, axis=1)   # rouge_scores = ROUGE.get_scores(row[16], row[13])

In [18]:
data_to_test['non_fb_25_scores'] = data_to_test.apply(get_rogue_scores, axis=1) # rouge_scores = ROUGE.get_scores(row[10], row[2])

In [20]:
data_to_test['non_fb_30_scores'] = data_to_test.apply(get_rogue_scores, axis=1) # rouge_scores = ROUGE.get_scores(row[11], row[2])

In [22]:
data_to_test['non_fb_35_scores'] = data_to_test.apply(get_rogue_scores, axis=1) # rouge_scores = ROUGE.get_scores(row[12], row[2])

In [ ]:
# Split the generated scores to format in the required manner
data_to_test['fb_r1_25_score'] = data_to_test['fb_25_scores'].apply(lambda x:x[0])
data_to_test['fb_rl_25_score'] = data_to_test['fb_25_scores'].apply(lambda x:x[1])
data_to_test['fb_r1_30_score'] = data_to_test['fb_30_scores'].apply(lambda x:x[0])
data_to_test['fb_rl_30_score'] = data_to_test['fb_30_scores'].apply(lambda x:x[1])
data_to_test['fb_r1_35_score'] = data_to_test['fb_35_scores'].apply(lambda x:x[0])
data_to_test['fb_rl_35_score'] = data_to_test['fb_35_scores'].apply(lambda x:x[1])
data_to_test['non_fb_r1_25_score'] = data_to_test['non_fb_25_scores'].apply(lambda x:x[0])
data_to_test['non_fb_rl_25_score'] = data_to_test['non_fb_25_scores'].apply(lambda x:x[1])
data_to_test['non_fb_r1_30_score'] = data_to_test['non_fb_30_scores'].apply(lambda x:x[0])
data_to_test['non_fb_rl_30_score'] = data_to_test['non_fb_30_scores'].apply(lambda x:x[1])
data_to_test['non_fb_r1_35_score'] = data_to_test['non_fb_35_scores'].apply(lambda x:x[0])
data_to_test['non_fb_rl_35_score'] = data_to_test['non_fb_35_scores'].apply(lambda x:x[1])

In [29]:
# Save file for future references
data_to_test.to_excel('/content/drive/MyDrive/scores_all_complete.xlsx', index=False)

In [36]:
# Select only the scores to find the means
only_scores = data_to_test.iloc[:,-12:]
only_scores.describe()

,fb_r1_25_score,fb_rl_25_score,fb_r1_30_score,fb_rl_30_score,fb_r1_35_score,fb_rl_35_score,non_fb_r1_25_score,non_fb_rl_25_score,non_fb_r1_30_score,non_fb_rl_30_score,non_fb_r1_35_score,non_fb_rl_35_score
count,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000
mean,0.286904,0.263419,0.314593,0.289201,0.339918,0.312618,0.365320,0.337778,0.380252,0.354347,0.394339,0.369475
std,0.077814,0.075889,0.077864,0.075333,0.081087,0.079673,0.143784,0.134333,0.145498,0.136971,0.148653,0.140817
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.252874,0.232044,0.284722,0.260000,0.305970,0.280303,0.275229,0.252632,0.286885,0.266667,0.297030,0.278689
50%,0.287770,0.264423,0.320000,0.293617,0.344595,0.316832,0.368421,0.335821,0.384615,0.358025,0.400000,0.373418
75%,0.324675,0.298137,0.354167,0.327189,0.384236,0.352657,0.458333,0.428571,0.477273,0.446809,0.489796,0.460000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.800000,0.785714,0.750000,0.750000,0.800000,0.757576